# Generated by Django 4.1 on 2024-03-25 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("basic_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofileinfo",
            old_name="postfolio_site",
            new_name="portfolio_site",
        ),
    ]
